name: My project build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Standard Checkout
        uses: actions/checkout@v3

      - name: Get short commit sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Maven build
        run: mvn -B package --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Get Project Version from pom.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getPomVersion

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "*.jar"
          draft: false
          prerelease: false
          tag: ${{ steps.getPomVersion.outputs.version }}-${{ steps.vars.outputs.sha_short }}
          body: ${{ github.event.head_commit.message }}
